{"metadata":{"kernelspec":{"language":"python","display_name":"Python 3","name":"python3"},"language_info":{"name":"python","version":"3.10.13","mimetype":"text/x-python","codemirror_mode":{"name":"ipython","version":3},"pygments_lexer":"ipython3","nbconvert_exporter":"python","file_extension":".py"},"kaggle":{"accelerator":"none","dataSources":[],"isInternetEnabled":true,"language":"python","sourceType":"notebook","isGpuEnabled":false}},"nbformat_minor":4,"nbformat":4,"cells":[{"cell_type":"code","source":"!python3 -m pip install --upgrade pip\n!git clone https://github.com/cg123/mergekit.git\n!cd mergekit && pip install -q -e .","metadata":{"execution":{"iopub.status.busy":"2024-05-22T13:25:43.967221Z","iopub.execute_input":"2024-05-22T13:25:43.967633Z","iopub.status.idle":"2024-05-22T13:26:51.273960Z","shell.execute_reply.started":"2024-05-22T13:25:43.967592Z","shell.execute_reply":"2024-05-22T13:26:51.272989Z"},"trusted":true},"execution_count":3,"outputs":[{"name":"stdout","text":"Requirement already satisfied: pip in /opt/conda/lib/python3.10/site-packages (23.3.2)\nCollecting pip\n  Downloading pip-24.0-py3-none-any.whl.metadata (3.6 kB)\nDownloading pip-24.0-py3-none-any.whl (2.1 MB)\n\u001b[2K   \u001b[90m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\u001b[0m \u001b[32m2.1/2.1 MB\u001b[0m \u001b[31m48.3 MB/s\u001b[0m eta \u001b[36m0:00:00\u001b[0m00:01\u001b[0m\n\u001b[?25hInstalling collected packages: pip\n  Attempting uninstall: pip\n    Found existing installation: pip 23.3.2\n    Uninstalling pip-23.3.2:\n      Successfully uninstalled pip-23.3.2\nSuccessfully installed pip-24.0\nCloning into 'mergekit'...\nremote: Enumerating objects: 1928, done.\u001b[K\nremote: Counting objects: 100% (1191/1191), done.\u001b[K\nremote: Compressing objects: 100% (511/511), done.\u001b[K\nremote: Total 1928 (delta 940), reused 777 (delta 679), pack-reused 737\u001b[K\nReceiving objects: 100% (1928/1928), 572.86 KiB | 5.67 MiB/s, done.\nResolving deltas: 100% (1318/1318), done.\n\u001b[31mERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.\nkeras-cv 0.8.2 requires keras-core, which is not installed.\nkeras-nlp 0.9.3 requires keras-core, which is not installed.\nbeatrix-jupyterlab 2023.128.151533 requires jupyterlab~=3.6.0, but you have jupyterlab 4.1.6 which is incompatible.\nmomepy 0.7.0 requires shapely>=2, but you have shapely 1.8.5.post1 which is incompatible.\nspopt 0.6.0 requires shapely>=2.0.1, but you have shapely 1.8.5.post1 which is incompatible.\nydata-profiling 4.6.4 requires numpy<1.26,>=1.16.0, but you have numpy 1.26.4 which is incompatible.\u001b[0m\u001b[31m\n\u001b[0m","output_type":"stream"}]},{"cell_type":"code","source":"from huggingface_hub import notebook_login as hfl\nhfl()","metadata":{"execution":{"iopub.status.busy":"2024-05-22T13:27:21.958794Z","iopub.execute_input":"2024-05-22T13:27:21.959621Z","iopub.status.idle":"2024-05-22T13:27:22.224572Z","shell.execute_reply.started":"2024-05-22T13:27:21.959583Z","shell.execute_reply":"2024-05-22T13:27:22.223730Z"},"trusted":true},"execution_count":4,"outputs":[{"output_type":"display_data","data":{"text/plain":"VBox(children=(HTML(value='<center> <img\\nsrc=https://huggingface.co/front/assets/huggingface_logo-noborder.sv…","application/vnd.jupyter.widget-view+json":{"version_major":2,"version_minor":0,"model_id":"90fe90662d2d455da59beb23726b7fb0"}},"metadata":{}}]},{"cell_type":"code","source":"config = \"\"\"\nslices:\n    - sources:\n        - model: google/codegemma-7b-it\n          layer_range: [0, 28]\n        - model: codellama/CodeLlama-7b-Instruct-hf\n          layer_range: [0, 28]\nparameters:\n    t:\n        - filter: self_attn\n          value: [0, 0.5, 0.3, 0.7, 1]\n        - filter: mlp\n          value: [1, 0.5, 0.7, 0.3, 0]\n        - value: 0.5 # Fallback for the rest of the tensors\nbase_model: google/codegemma-7b-it\nmerge_method: slerp\ndtype: float16\n\"\"\"","metadata":{"execution":{"iopub.status.busy":"2024-05-22T13:49:59.256906Z","iopub.execute_input":"2024-05-22T13:49:59.257311Z","iopub.status.idle":"2024-05-22T13:49:59.262638Z","shell.execute_reply.started":"2024-05-22T13:49:59.257268Z","shell.execute_reply":"2024-05-22T13:49:59.261664Z"},"trusted":true},"execution_count":16,"outputs":[]},{"cell_type":"code","source":"with open(\"config.yaml\", \"w\") as f:\n    f.write(config)","metadata":{"execution":{"iopub.status.busy":"2024-05-22T13:49:59.869867Z","iopub.execute_input":"2024-05-22T13:49:59.870218Z","iopub.status.idle":"2024-05-22T13:49:59.875476Z","shell.execute_reply.started":"2024-05-22T13:49:59.870191Z","shell.execute_reply":"2024-05-22T13:49:59.874625Z"},"trusted":true},"execution_count":17,"outputs":[]},{"cell_type":"code","source":"!mergekit-yaml config.yaml output-dir --allow-crimes --copy-tokenizer --out-shard-size 1B --low-cpu-memory --write-model-card --lazy-unpickle","metadata":{"scrolled":true,"execution":{"iopub.status.busy":"2024-05-22T13:50:03.532991Z","iopub.execute_input":"2024-05-22T13:50:03.533679Z","iopub.status.idle":"2024-05-22T13:50:26.325159Z","shell.execute_reply.started":"2024-05-22T13:50:03.533647Z","shell.execute_reply":"2024-05-22T13:50:26.324073Z"},"trusted":true},"execution_count":18,"outputs":[{"name":"stdout","text":"Warmup loader cache:   0%|                                | 0/2 [00:00<?, ?it/s]\nFetching 11 files: 100%|█████████████████████| 11/11 [00:00<00:00, 85439.53it/s]\u001b[A\nWarmup loader cache:  50%|████████████            | 1/2 [00:00<00:00,  4.13it/s]\nFetching 10 files: 100%|█████████████████████| 10/10 [00:00<00:00, 57852.47it/s]\u001b[A\nWarmup loader cache: 100%|████████████████████████| 2/2 [00:00<00:00,  4.18it/s]\nExecuting graph:   1%|▏                        | 9/1272 [00:11<27:23,  1.30s/it]\nTraceback (most recent call last):\n  File \"/opt/conda/bin/mergekit-yaml\", line 8, in <module>\n    sys.exit(main())\n  File \"/opt/conda/lib/python3.10/site-packages/click/core.py\", line 1157, in __call__\n    return self.main(*args, **kwargs)\n  File \"/opt/conda/lib/python3.10/site-packages/click/core.py\", line 1078, in main\n    rv = self.invoke(ctx)\n  File \"/opt/conda/lib/python3.10/site-packages/click/core.py\", line 1434, in invoke\n    return ctx.invoke(self.callback, **ctx.params)\n  File \"/opt/conda/lib/python3.10/site-packages/click/core.py\", line 783, in invoke\n    return __callback(*args, **kwargs)\n  File \"/kaggle/working/mergekit/mergekit/options.py\", line 82, in wrapper\n    f(*args, **kwargs)\n  File \"/kaggle/working/mergekit/mergekit/scripts/run_yaml.py\", line 47, in main\n    run_merge(\n  File \"/kaggle/working/mergekit/mergekit/merge.py\", line 92, in run_merge\n    for _task, value in exec.run(quiet=options.quiet):\n  File \"/kaggle/working/mergekit/mergekit/graph.py\", line 197, in run\n    res = task.execute(**arguments)\n  File \"/kaggle/working/mergekit/mergekit/merge_methods/slerp.py\", line 57, in execute\n    slerp(\n  File \"/kaggle/working/mergekit/mergekit/merge_methods/slerp.py\", line 134, in slerp\n    dot = np.sum(v0 * v1)\nValueError: operands could not be broadcast together with shapes (3072,) (4096,) \n","output_type":"stream"}]},{"cell_type":"code","source":"","metadata":{"scrolled":true},"execution_count":null,"outputs":[]}]}